// AUTO-GENERATED from SMSPVA official service list (docs.smspva.com)
// code = SMSPVA "service" param (e.g. opt29 = Telegram) used directly in API calls
// hasCustomLogo = false means SMSPVA has no distinct icon for it (falls back to initials badge)
import { SmspvaService } from "./types";

export const SMSPVA_SERVICES: SmspvaService[] = [
  { id: "1-openai-api-chatgpt-dall-e-2", code: "opt132", name: "1 OpenAI API (chatGPT, DALL-e 2)", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/open_api.png", hasCustomLogo: true },
  { id: "1cupis-ru", code: "opt251", name: "1cupis.ru", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt251_66e125780140b.jpg", hasCustomLogo: true },
  { id: "22bet", code: "opt224", name: "22bet", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt224_66068262d71e1.png", hasCustomLogo: true },
  { id: "888casino", code: "opt22", name: "888casino", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt22_655cdab4dbd01.jpg", hasCustomLogo: true },
  { id: "abbott", code: "opt242", name: "Abbott", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt242_668e3f109c6d0.png", hasCustomLogo: true },
  { id: "adidas-nike", code: "opt86", name: "Adidas & Nike", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/nike.png", hasCustomLogo: true },
  { id: "airbnb", code: "opt46", name: "Airbnb", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/airbnb.ico", hasCustomLogo: true },
  { id: "alibaba-taobao-1688-com", code: "opt61", name: "Alibaba (Taobao, 1688.com)", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/taobao.png", hasCustomLogo: true },
  { id: "amazon", code: "opt44", name: "Amazon", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/amazon.ico", hasCustomLogo: true },
  { id: "american-airlines", code: "opt272", name: "American Airlines", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt272_6a107319441b0.jpg", hasCustomLogo: true },
  { id: "aol", code: "opt10", name: "AOL", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/aol.png", hasCustomLogo: true },
  { id: "apple", code: "opt131", name: "Apple", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/apple.ico", hasCustomLogo: true },
  { id: "astropay", code: "opt256", name: "Astropay", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt256_6736ad34d8521.jpg", hasCustomLogo: true },
  { id: "autocosmos-com", code: "opt143", name: "autocosmos.com", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt143_655cd99229dba.jpg", hasCustomLogo: true },
  { id: "avito", code: "opt59", name: "Avito", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/avito.png", hasCustomLogo: true },
  { id: "badoo", code: "opt56", name: "Badoo", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/badoo.png", hasCustomLogo: true },
  { id: "bandus", code: "opt209", name: "BANDUS", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt209_65801c9cb87c2.png", hasCustomLogo: true },
  { id: "bazos-sk", code: "opt138", name: "Bazos.sk", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt138_655b124b5ce53.png", hasCustomLogo: true },
  { id: "bc-game", code: "opt262", name: "BC GAME", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt262_6794cd0476adc.jpg", hasCustomLogo: true },
  { id: "beget-com", code: "opt187", name: "Beget.com", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt187_655ca45c48943.png", hasCustomLogo: true },
  { id: "best-buy", code: "opt252", name: "Best Buy", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt252_6729d8ff99907.png", hasCustomLogo: true },
  { id: "bet365", code: "opt17", name: "bet365", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/bet365.png", hasCustomLogo: true },
  { id: "betano-all-countries", code: "opt192", name: "Betano (all countries)", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt192_656ef71f9770d.jpg", hasCustomLogo: true },
  { id: "betfair", code: "opt25", name: "BetFair", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/betfair.png", hasCustomLogo: true },
  { id: "betmgm", code: "opt223", name: "Betmgm", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt223_6605370e23fca.jpg", hasCustomLogo: true },
  { id: "bitpanda", code: "opt237", name: "Bitpanda", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt237_66617efa9abc1.png", hasCustomLogo: true },
  { id: "blizzard", code: "opt78", name: "Blizzard", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/blizzard.ico", hasCustomLogo: true },
  { id: "blsspain-russia-com", code: "opt135", name: "blsspain-russia.com", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt135_66630426565d2.png", hasCustomLogo: true },
  { id: "bolt", code: "opt81", name: "Bolt", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/bolt.png", hasCustomLogo: true },
  { id: "brevo", code: "opt217", name: "Brevo", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt217_65c5907f769ab.png", hasCustomLogo: true },
  { id: "bumble", code: "opt145", name: "bumble", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt145_666304863ecdf.png", hasCustomLogo: true },
  { id: "bunq", code: "opt199", name: "bunq", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt199_6578544374956.png", hasCustomLogo: true },
  { id: "bwin", code: "opt137", name: "bwin", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt137_666304cb5c4b4.png", hasCustomLogo: true },
  { id: "caliente", code: "opt267", name: "Caliente", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt267_680f09c6e0021.jpg", hasCustomLogo: true },
  { id: "capital-one-shopping", code: "opt266", name: "Capital One Shopping", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt266_67eba35b6a272.png", hasCustomLogo: true },
  { id: "careem", code: "opt89", name: "Careem", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/careem.png", hasCustomLogo: true },
  { id: "casa-pariurilor", code: "opt255", name: "Casa Pariurilor", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt255_6731d0f5bc67e.jpg", hasCustomLogo: true },
  { id: "casa-it", code: "opt148", name: "casa.it", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt148_6663051dc7573.png", hasCustomLogo: true },
  { id: "cash-app", code: "opt226", name: "Cash App", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt226_6618e1e656bbe.png", hasCustomLogo: true },
  { id: "cashrewards", code: "opt214", name: "Cashrewards", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt214_658020faa7c45.png", hasCustomLogo: true },
  { id: "casino-plus", code: "opt201", name: "Casino Plus", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt201_657854eb0dc5e.jpg", hasCustomLogo: true },
  { id: "chotot", code: "opt176", name: "ChoTot", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt176_655c9e402576d.jpg", hasCustomLogo: true },
  { id: "citymobil", code: "opt76", name: "CityMobil", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/cmobil.ico", hasCustomLogo: true },
  { id: "claude-anthropic", code: "opt196", name: "Claude (Anthropic)", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt196_65703c0312d2f.png", hasCustomLogo: true },
  { id: "clubhouse", code: "opt98", name: "Clubhouse", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt98_66630597a465a.png", hasCustomLogo: true },
  { id: "coinbase", code: "opt112", name: "CoinBase", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/another.png", hasCustomLogo: false },
  { id: "contact", code: "opt51", name: "CONTACT", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/contact.ico", hasCustomLogo: true },
  { id: "credit-karma", code: "opt124", name: "Credit Karma", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt124_666305f26e9d5.png", hasCustomLogo: true },
  { id: "crigslistapp", code: "opt26", name: "CrigslistApp", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/another.png", hasCustomLogo: false },
  { id: "cupidmedia", code: "opt157", name: "CupidMedia", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt157_65573a7277542.png", hasCustomLogo: true },
  { id: "czech-email-services", code: "opt150", name: "Czech email services", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt150_66630661755a6.png", hasCustomLogo: true },
  { id: "deliveroo", code: "opt53", name: "Deliveroo", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt53_666306bc585f2.png", hasCustomLogo: true },
  { id: "denimapp", code: "opt204", name: "DenimApp", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt204_65785f8da5185.png", hasCustomLogo: true },
  { id: "didi", code: "opt92", name: "DiDi", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/didi.ico", hasCustomLogo: true },
  { id: "discord", code: "opt45", name: "Discord", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/discord.ico", hasCustomLogo: true },
  { id: "distrokid", code: "opt232", name: "DistroKid", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt232_66277a123c10d.png", hasCustomLogo: true },
  { id: "doordash", code: "opt40", name: "Doordash", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt40_6663073ae9b40.png", hasCustomLogo: true },
  { id: "drom-ru", code: "opt32", name: "Drom.RU", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/dromru.png", hasCustomLogo: true },
  { id: "drug-vokrug", code: "opt31", name: "Drug Vokrug", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/drug.png", hasCustomLogo: true },
  { id: "dundle", code: "opt136", name: "dundle", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt136_666307d9f04d5.png", hasCustomLogo: true },
  { id: "easypay", code: "opt21", name: "EasyPay", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt21_6663082ecc1bc.png", hasCustomLogo: true },
  { id: "emag-ro", code: "opt274", name: "Emag.ro", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt274_6a4e3aaad4232.png", hasCustomLogo: true },
  { id: "eneba", code: "opt200", name: "ENEBA", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt200_65785487ae8a7.jpg", hasCustomLogo: true },
  { id: "esx-abonamentesali-ro", code: "opt248", name: "ESX (abonamentesali.ro)", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt248_66becf1d2c4fa.png", hasCustomLogo: true },
  { id: "eurobet", code: "opt141", name: "EUROBET", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt141_6663088f13652.png", hasCustomLogo: true },
  { id: "facebook", code: "opt2", name: "Facebook", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/fb.png", hasCustomLogo: true },
  { id: "fastmail", code: "opt43", name: "FastMail", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/fastmail.png", hasCustomLogo: true },
  { id: "fbet", code: "opt215", name: "Fbet", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt215_658023186e69f.png", hasCustomLogo: true },
  { id: "feeld", code: "opt159", name: "Feeld", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt159_65573af945053.png", hasCustomLogo: true },
  { id: "fiverr", code: "opt6", name: "Fiverr", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt6_666308f6e6723.png", hasCustomLogo: true },
  { id: "fontbet", code: "opt139", name: "fontbet", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt139_666309490c426.png", hasCustomLogo: true },
  { id: "foodora", code: "opt189", name: "foodora", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt189_655ca5f13c9b3.png", hasCustomLogo: true },
  { id: "foodpanda", code: "opt115", name: "foodpanda", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/foodpanda.png", hasCustomLogo: true },
  { id: "fortuna", code: "opt221", name: "Fortuna", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt221_65f2a3c9c749c.png", hasCustomLogo: true },
  { id: "fotostrana", code: "opt13", name: "Fotostrana", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/fotostrana.png", hasCustomLogo: true },
  { id: "funpay", code: "opt142", name: "funpay", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt142_6663098613401.png", hasCustomLogo: true },
  { id: "g2a-com", code: "opt68", name: "G2A.COM", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/g2a.jpg", hasCustomLogo: true },
  { id: "gameflip", code: "opt77", name: "Gameflip", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/paxful.png", hasCustomLogo: true },
  { id: "gamers-set-offgamers-com-g2a-com-seagm-com", code: "opt28", name: "Gamers set (offgamers.com, G2A.com, seagm.com)", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt28_666309e76d144.png", hasCustomLogo: true },
  { id: "getsbet-ro", code: "opt179", name: "GetsBet.ro", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt179_655ca016d7361.png", hasCustomLogo: true },
  { id: "gettaxi", code: "opt35", name: "GetTaxi", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/gettaxi.png", hasCustomLogo: true },
  { id: "ggbet", code: "opt188", name: "GGbet", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt188_655ca591689ef.png", hasCustomLogo: true },
  { id: "ggpokeruk", code: "opt229", name: "GGPokerUK", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt229_6627781a653e5.jpg", hasCustomLogo: true },
  { id: "giocodigitale-it", code: "opt85", name: "giocodigitale.it", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt85_66630a3f4b444.png", hasCustomLogo: true },
  { id: "glovo-raketa", code: "opt108", name: "Glovo & Raketa", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/glovoraketa.ico", hasCustomLogo: true },
  { id: "goldbet-it", code: "opt240", name: "goldbet.it", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt240_66879c1ad054d.jpg", hasCustomLogo: true },
  { id: "google-youtube-gmail", code: "opt1", name: "Google (YouTube, Gmail)", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/gmail.png", hasCustomLogo: true },
  { id: "google-chat", code: "opt271", name: "Google Chat", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt271_69e1e2cdd95c7.png", hasCustomLogo: true },
  { id: "google-messenger", code: "opt259", name: "Google Messenger", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt259_6752aa00ab5b1.png", hasCustomLogo: true },
  { id: "google-voice", code: "opt140", name: "Google Voice", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/gmail.png", hasCustomLogo: true },
  { id: "grabtaxi", code: "opt30", name: "GrabTaxi", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/grabtaxi.png", hasCustomLogo: true },
  { id: "grailed", code: "opt420", name: "Grailed", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/grailed.png", hasCustomLogo: true },
  { id: "grindr", code: "opt110", name: "Grindr", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/grindr.ico", hasCustomLogo: true },
  { id: "h1nge", code: "opt120", name: "H1nge", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/another.png", hasCustomLogo: false },
  { id: "happn", code: "opt155", name: "Happn", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt155_655716304f898.png", hasCustomLogo: true },
  { id: "hellotalk", code: "opt203", name: "HelloTalk", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt203_65785efc1689c.png", hasCustomLogo: true },
  { id: "hepsiburada", code: "opt238", name: "hepsiburada", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt238_667a2c8e7a580.png", hasCustomLogo: true },
  { id: "hey", code: "opt216", name: "Hey", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt216_65a5f5900f846.png", hasCustomLogo: true },
  { id: "hopper", code: "opt144", name: "hopper", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt144_66630aea202ae.png", hasCustomLogo: true },
  { id: "huawei", code: "opt166", name: "HUAWEI", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt166_6556153845310.png", hasCustomLogo: true },
  { id: "icard", code: "opt103", name: "ICard", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/icard.png", hasCustomLogo: true },
  { id: "idealista-com", code: "opt165", name: "idealista.com", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt165_66630b4899f30.png", hasCustomLogo: true },
  { id: "ifood", code: "opt55", name: "ifood", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt55_66630b89aff92.png", hasCustomLogo: true },
  { id: "imo", code: "opt111", name: "IMO", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/imo.png", hasCustomLogo: true },
  { id: "inbox-lv", code: "opt167", name: "inbox.lv", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt167_654de72ab4120.png", hasCustomLogo: true },
  { id: "inboxdollars", code: "opt118", name: "Inboxdollars", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/inboxdollars.png", hasCustomLogo: true },
  { id: "instagram-threads", code: "opt16", name: "Instagram (+Threads)", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/instagram.png", hasCustomLogo: true },
  { id: "ipsos", code: "opt193", name: "Ipsos", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt193_65702a87b9141.png", hasCustomLogo: true },
  { id: "iqos", code: "opt243", name: "IQOS", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt243_6694df3aa6431.png", hasCustomLogo: true },
  { id: "jd-com", code: "opt94", name: "JD.com", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/jd.ico", hasCustomLogo: true },
  { id: "kakaotalk", code: "opt71", name: "KakaoTalk", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/kakao.ico", hasCustomLogo: true },
  { id: "klarna", code: "opt175", name: "Klarna", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt175_655c993f936a3.png", hasCustomLogo: true },
  { id: "kleinanzeigen-de", code: "opt152", name: "kleinanzeigen.de", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt152_66630bd9c5aae.png", hasCustomLogo: true },
  { id: "koronapay", code: "opt99", name: "KoronaPay", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt99_66630c05209e0.png", hasCustomLogo: true },
  { id: "kuper-sbermarket", code: "opt97", name: "Kuper (SberMarket)", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/sbermarket.ico", hasCustomLogo: true },
  { id: "kwiff-com", code: "opt129", name: "kwiff.com", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/kwiff.ico", hasCustomLogo: true },
  { id: "lajumate-ro", code: "opt195", name: "Lajumate.ro", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt195_6570395fe0b3f.png", hasCustomLogo: true },
  { id: "lalamove", code: "opt180", name: "Lalamove", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt180_655ca0b0de4b5.png", hasCustomLogo: true },
  { id: "laposte", code: "opt182", name: "LAPOSTE", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt182_655ca1d5514bf.png", hasCustomLogo: true },
  { id: "lasvegas-ro", code: "opt222", name: "LASVEGAS.RO", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt222_65f2a3fbe362f.jpg", hasCustomLogo: true },
  { id: "lazada", code: "opt60", name: "Lazada", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/lazada.png", hasCustomLogo: true },
  { id: "leboncoin", code: "opt164", name: "Leboncoin", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt164_65571a978d6e3.png", hasCustomLogo: true },
  { id: "line-messenger", code: "opt37", name: "Line Messenger", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/line.ico", hasCustomLogo: true },
  { id: "linkedin", code: "opt8", name: "LinkedIn", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/linkedin.png", hasCustomLogo: true },
  { id: "linode", code: "opt245", name: "Linode", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt245_66a453a3a5454.png", hasCustomLogo: true },
  { id: "livescore", code: "opt42", name: "LiveScore", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/livescore.png", hasCustomLogo: true },
  { id: "localbitcoins", code: "opt105", name: "LocalBitcoins", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/localbitcoins.png", hasCustomLogo: true },
  { id: "locanto-com", code: "opt114", name: "Locanto.com", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/locanto.jpg", hasCustomLogo: true },
  { id: "lyft", code: "opt75", name: "Lyft", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/lyft.ico", hasCustomLogo: true },
  { id: "magnit", code: "opt126", name: "Magnit", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt126_66630c9094b53.png", hasCustomLogo: true },
  { id: "mail-ru", code: "opt33", name: "Mail.RU", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/mail_black.png", hasCustomLogo: true },
  { id: "mail-ru-group", code: "opt4", name: "Mail.ru Group", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/mailru.png", hasCustomLogo: true },
  { id: "mamba", code: "opt100", name: "Mamba", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/mamba.ico", hasCustomLogo: true },
  { id: "marktplaats", code: "opt171", name: "Marktplaats", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt171_6556077d514ef.jpg", hasCustomLogo: true },
  { id: "match", code: "opt250", name: "Match", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt250_66e00cff34986.png", hasCustomLogo: true },
  { id: "maxline-by", code: "opt219", name: "maxline.by", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt219_65d85aacb2f0a.png", hasCustomLogo: true },
  { id: "michat", code: "opt96", name: "MiChat", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/michat.png", hasCustomLogo: true },
  { id: "microsoft-azure-bing-skype-etc", code: "opt15", name: "Microsoft (Azure, Bing, Skype, etc)", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/ms.png", hasCustomLogo: true },
  { id: "mobilede", code: "opt156", name: "mobileDE", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt156_655739cc1a3db.png", hasCustomLogo: true },
  { id: "momo", code: "opt184", name: "MOMO", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt184_655ca302f1b2a.png", hasCustomLogo: true },
  { id: "monese", code: "opt121", name: "Monese", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/monese.png", hasCustomLogo: true },
  { id: "moneylion", code: "opt47", name: "MoneyLion", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt47_66630ce033c02.png", hasCustomLogo: true },
  { id: "monster-energy", code: "opt254", name: "Monster Energy", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt254_67316d1b182a8.png", hasCustomLogo: true },
  { id: "mpsellers", code: "opt197", name: "MPSellers", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt197_65785390376e5.png", hasCustomLogo: true },
  { id: "mrgreen", code: "opt211", name: "MrGreen", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt211_65801f33ea021.png", hasCustomLogo: true },
  { id: "ms-office-365", code: "opt7", name: "MS Office 365", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/office365.ico", hasCustomLogo: true },
  { id: "myopinions-erewards", code: "opt0", name: "myopinions & erewards", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt0_66630d21d0979.png", hasCustomLogo: true },
  { id: "naver", code: "opt73", name: "Naver", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/naver.ico", hasCustomLogo: true },
  { id: "nectar", code: "opt198", name: "Nectar", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt198_657853fe74459.png", hasCustomLogo: true },
  { id: "neosurf", code: "opt269", name: "Neosurf", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt269_68ee0c8f8f88f.png", hasCustomLogo: true },
  { id: "netbet", code: "opt95", name: "NetBet", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/netbet.ico", hasCustomLogo: true },
  { id: "neteller", code: "opt116", name: "Neteller", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/neteller.ico", hasCustomLogo: true },
  { id: "netflix", code: "opt101", name: "Netflix", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/netflix.ico", hasCustomLogo: true },
  { id: "nhncloud", code: "opt202", name: "NHNCloud", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt202_65785e5c99854.jpg", hasCustomLogo: true },
  { id: "nhncorp", code: "opt177", name: "NHNcorp (강남언니)", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt177_655c9ed951f22.png", hasCustomLogo: true },
  { id: "nico", code: "opt119", name: "Nico", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt119_66630d716253d.png", hasCustomLogo: true },
  { id: "novibet-com", code: "opt151", name: "novibet.com", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt151_66630d9ecbf7a.png", hasCustomLogo: true },
  { id: "od", code: "opt5", name: "OD", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/ok.png", hasCustomLogo: true },
  { id: "offerup", code: "opt113", name: "OfferUp", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/offerup.png", hasCustomLogo: true },
  { id: "okcup-d", code: "opt230", name: "OkCupᎥd", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/another.png", hasCustomLogo: false },
  { id: "okx", code: "opt228", name: "OKX", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt228_662776c65aa6f.png", hasCustomLogo: true },
  { id: "olx", code: "opt70", name: "OLX", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/olx.png", hasCustomLogo: true },
  { id: "onet-pl-onet-konto", code: "opt241", name: "onet.pl (Onet Konto)", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt241_668b5cc59eed1.png", hasCustomLogo: true },
  { id: "other-no-guarantee", code: "opt19", name: "OTHER (no guarantee)", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/another.png", hasCustomLogo: false },
  { id: "ourtime", code: "opt212", name: "OurTime", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt212_65801fe22156e.png", hasCustomLogo: true },
  { id: "outlier", code: "opt246", name: "Outlier", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt246_66a75c27314ca.jpg", hasCustomLogo: true },
  { id: "ozon-ru", code: "opt181", name: "OZON.ru", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt181_655ca17d51618.jpg", hasCustomLogo: true },
  { id: "p0f", code: "opt84", name: "P0F", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt84.jpg", hasCustomLogo: true },
  { id: "paddy-power", code: "opt109", name: "Paddy Power", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/paddypower.png", hasCustomLogo: true },
  { id: "pamestoixima", code: "opt273", name: "pamestoixima", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt273_6a3e50db12be7.png", hasCustomLogo: true },
  { id: "papajohns", code: "opt27", name: "PapaJohns", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/dodopizza.png", hasCustomLogo: true },
  { id: "pari-ru", code: "opt169", name: "Pari.ru", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt169_65573ba54b8e3.png", hasCustomLogo: true },
  { id: "parimatch", code: "opt3", name: "Parimatch", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt3_66630e40af702.png", hasCustomLogo: true },
  { id: "parions-sport", code: "opt260", name: "Parions Sport", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt260_6757d7981eb06.png", hasCustomLogo: true },
  { id: "payoneer", code: "opt162", name: "Payoneer", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt162_655739fca1cbc.png", hasCustomLogo: true },
  { id: "paypal-ebay", code: "opt83", name: "PayPal + Ebay", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/paypal.ico", hasCustomLogo: true },
  { id: "paysafecard", code: "opt122", name: "Paysafecard", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt122_66630e6507056.png", hasCustomLogo: true },
  { id: "paysend", code: "opt183", name: "PAYSEND", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt183_655ca25582e36.png", hasCustomLogo: true },
  { id: "pm-by", code: "opt149", name: "pm.by", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt149_666315091b834.png", hasCustomLogo: true },
  { id: "pokemon-center-online", code: "opt268", name: "Pokemon Center Online", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt268_6895d0976c521.png", hasCustomLogo: true },
  { id: "profee-com", code: "opt263", name: "Profee.com", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt263_679762edd8ecd.jpg", hasCustomLogo: true },
  { id: "prom-ua", code: "opt107", name: "Prom.UA", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/promua.ico", hasCustomLogo: true },
  { id: "proton-mail", code: "opt57", name: "Proton Mail", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/protonmail.ico", hasCustomLogo: true },
  { id: "publi24", code: "opt207", name: "Publi24", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt207_657860f02ca12.png", hasCustomLogo: true },
  { id: "radquest", code: "opt247", name: "RadQuest", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt247_66aaf3ff6e25b.png", hasCustomLogo: true },
  { id: "rambler-ru", code: "opt154", name: "Rambler.ru", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt154_65573c1d9ffef.png", hasCustomLogo: true },
  { id: "reddit", code: "opt265", name: "Reddit", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt265_67c7d5277a1ae.png", hasCustomLogo: true },
  { id: "remitly", code: "opt257", name: "Remitly", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt257_673bfe0ad3094.png", hasCustomLogo: true },
  { id: "revolut", code: "opt133", name: "Revolut", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt133_6663154f63220.png", hasCustomLogo: true },
  { id: "roomster", code: "opt153", name: "ROOMSTER", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt153_65573b772b37d.png", hasCustomLogo: true },
  { id: "royal-canin", code: "opt170", name: "Royal Canin", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt170_65573bf46bb42.png", hasCustomLogo: true },
  { id: "rusdate", code: "opt186", name: "RusDate", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt186_655ca4149ac53.png", hasCustomLogo: true },
  { id: "samokat", code: "opt185", name: "Samokat", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt185_655ca34cacf3f.png", hasCustomLogo: true },
  { id: "samsung", code: "opt174", name: "Samsung", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt174_655c93471955e.png", hasCustomLogo: true },
  { id: "schibsted-konto", code: "opt134", name: "Schibsted-konto", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt134_66631584e443d.png", hasCustomLogo: true },
  { id: "shopee", code: "opt48", name: "Shopee", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/shopee.ico", hasCustomLogo: true },
  { id: "signal", code: "opt127", name: "Signal", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/signal.png", hasCustomLogo: true },
  { id: "sisal", code: "opt38", name: "Sisal", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt38_666315d27fd60.png", hasCustomLogo: true },
  { id: "skelbiu", code: "opt270", name: "Skelbiu", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt270_69b18763cffe8.png", hasCustomLogo: true },
  { id: "skout", code: "opt49", name: "Skout", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/skout.png", hasCustomLogo: true },
  { id: "skrill", code: "opt117", name: "Skrill", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/skrill.ico", hasCustomLogo: true },
  { id: "skybet", code: "opt275", name: "SkyBet", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt275_6a54a01151cab.png", hasCustomLogo: true },
  { id: "snapchat", code: "opt90", name: "Snapchat", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/snapchat.ico", hasCustomLogo: true },
  { id: "snkrdunk", code: "opt190", name: "SNKRDUNK", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt190_66631618b8f0f.png", hasCustomLogo: true },
  { id: "solitaire", code: "opt234", name: "Solitaire", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt234_66277c31c97c6.jpg", hasCustomLogo: true },
  { id: "steam", code: "opt58", name: "Steam", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/steam.png", hasCustomLogo: true },
  { id: "subito-it", code: "opt146", name: "subito.it", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt146_6663166e99628.png", hasCustomLogo: true },
  { id: "sumup", code: "opt258", name: "SumUp", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt258_673c00ec21c15.png", hasCustomLogo: true },
  { id: "superbet", code: "opt249", name: "Superbet", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt249_66cd532e50a46.jpg", hasCustomLogo: true },
  { id: "swagbucks", code: "opt125", name: "Swagbucks", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/swagbucks.ico", hasCustomLogo: true },
  { id: "t1nder", code: "opt9", name: "T1nder", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt9.jpg", hasCustomLogo: true },
  { id: "tango", code: "opt82", name: "Tango", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/tango.jpg", hasCustomLogo: true },
  { id: "tank-ru", code: "opt161", name: "TANK.RU", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt161_65573bd0db8b8.jpg", hasCustomLogo: true },
  { id: "taptap", code: "opt239", name: "Taptap", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt239_6686a402c737d.jpg", hasCustomLogo: true },
  { id: "taxi-maksim", code: "opt74", name: "Taxi Maksim", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/taxi_maxim.png", hasCustomLogo: true },
  { id: "telegram", code: "opt29", name: "Telegram", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/telegram.png", hasCustomLogo: true },
  { id: "tencent-qq", code: "opt34", name: "Tencent QQ", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/qq.png", hasCustomLogo: true },
  { id: "ticketmaster", code: "opt52", name: "Ticketmaster", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/ticketmaster.ico", hasCustomLogo: true },
  { id: "tiktok", code: "opt104", name: "TikTok", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/tiktok.png", hasCustomLogo: true },
  { id: "tlscontact", code: "opt235", name: "TLScontact", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt235_66277cfea7c12.png", hasCustomLogo: true },
  { id: "toloka-ai", code: "opt264", name: "Toloka.ai", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt264_67a5ce9411d06.png", hasCustomLogo: true },
  { id: "topcashback", code: "opt191", name: "TopCashback", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt191_656ef49a40563.jpg", hasCustomLogo: true },
  { id: "totogaming", code: "opt220", name: "TOTOGAMING", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt220_65f2a39a0ebef.jpg", hasCustomLogo: true },
  { id: "transfergo", code: "opt218", name: "TransferGo", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt218_65cdde639ba36.png", hasCustomLogo: true },
  { id: "truecaller", code: "opt233", name: "TrueCaller", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt233_66277b08f3960.png", hasCustomLogo: true },
  { id: "truth-social", code: "opt244", name: "Truth Social", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt244_6697a1805c2c2.png", hasCustomLogo: true },
  { id: "twilio", code: "opt66", name: "Twilio", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/twilio.png", hasCustomLogo: true },
  { id: "twitch", code: "opt205", name: "Twitch", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt205_657860147869a.png", hasCustomLogo: true },
  { id: "u-by-prodia", code: "opt160", name: "U By Prodia", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt160_65573ac5a1791.png", hasCustomLogo: true },
  { id: "uber", code: "opt72", name: "Uber", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/uber.jpg", hasCustomLogo: true },
  { id: "verse", code: "opt39", name: "Verse", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt39_666316ca23ffd.png", hasCustomLogo: true },
  { id: "viber", code: "opt11", name: "Viber", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/viber.png", hasCustomLogo: true },
  { id: "vinted", code: "opt130", name: "Vinted", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/vinted.png", hasCustomLogo: true },
  { id: "vk-no-guarantee", code: "opt69", name: "VK (no guarantee)", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/vk_black.png", hasCustomLogo: true },
  { id: "vonagevf", code: "opt178", name: "VonageVF", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt178_655c9fa709a13.png", hasCustomLogo: true },
  { id: "voov-meeting", code: "opt147", name: "VooV Meeting", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt147_6663171214afb.png", hasCustomLogo: true },
  { id: "waitomo", code: "opt213", name: "Waitomo", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt213_6580204be0c7e.jpg", hasCustomLogo: true },
  { id: "wallethub", code: "opt206", name: "WalletHub", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt206_65786091bfe43.png", hasCustomLogo: true },
  { id: "walmart", code: "opt227", name: "Walmart", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt227_66275f39aa809.png", hasCustomLogo: true },
  { id: "web-de", code: "opt172", name: "WEB.DE", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt172_655c87eca1f10.png", hasCustomLogo: true },
  { id: "webmoney-enum", code: "opt24", name: "WebMoney&ENUM", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/webmoney.png", hasCustomLogo: true },
  { id: "wechat", code: "opt67", name: "WeChat", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/wechat.png", hasCustomLogo: true },
  { id: "weebly", code: "opt54", name: "Weebly", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/weebly.png", hasCustomLogo: true },
  { id: "welo-data", code: "opt261", name: "Welo Data", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt261_675fc24f54025.png", hasCustomLogo: true },
  { id: "weststein", code: "opt80", name: "WESTSTEIN", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/weststein.ico", hasCustomLogo: true },
  { id: "whatnot", code: "opt231", name: "Whatnot", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt231_6627797fc0648.png", hasCustomLogo: true },
  { id: "whatsapp", code: "opt20", name: "WhatsAPP", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/whatsapp.png", hasCustomLogo: true },
  { id: "whoosh", code: "opt123", name: "Whoosh", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/whoosh.ico", hasCustomLogo: true },
  { id: "wing-money", code: "opt106", name: "Wing Money", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt106_66631774989da.png", hasCustomLogo: true },
  { id: "wise", code: "opt91", name: "Wise", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt91_666317b2b934e.png", hasCustomLogo: true },
  { id: "wolt", code: "opt163", name: "Wolt", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt163_655607e9a3566.jpg", hasCustomLogo: true },
  { id: "wooplus", code: "opt208", name: "WooPlus", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt208_6578614116272.png", hasCustomLogo: true },
  { id: "x-twitter", code: "opt41", name: "X (Twitter)", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/twitter.png", hasCustomLogo: true },
  { id: "x-world-wallet", code: "opt173", name: "X World Wallet", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt173_655c907dc253f.png", hasCustomLogo: true },
  { id: "yahoo", code: "opt65", name: "Yahoo", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/yahoo.png", hasCustomLogo: true },
  { id: "yalla-live", code: "opt88", name: "Yalla.live", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/yalla.png", hasCustomLogo: true },
  { id: "yandex-yoomoney", code: "opt23", name: "Yandex&YooMoney", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/yandex.png", hasCustomLogo: true },
  { id: "year13", code: "opt236", name: "Year13", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt236_66545076f0f9e.png", hasCustomLogo: true },
  { id: "zalo", code: "opt158", name: "Zalo", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt158_65560834b69e9.png", hasCustomLogo: true },
  { id: "zasilkovna", code: "opt225", name: "Zasilkovna", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt225_66068297c8f5e.png", hasCustomLogo: true },
  { id: "zoho", code: "opt93", name: "Zoho", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/zoho.png", hasCustomLogo: true },
  { id: "zoominfo", code: "opt194", name: "ZoomInfo", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt194_657030a853861.png", hasCustomLogo: true },
  { id: "zoosk", code: "opt253", name: "Zoosk", logoUrl: "https://smspva.com/templates/New_Design_Multilang/images/ico/opt253_672c28e72b044.png", hasCustomLogo: true },
];
