// Services supported by SMSPVA's Rental API (v1), confirmed from
// docs.smspva.com's Rental section.
//
// IMPORTANT: these "opt" codes are a SEPARATE numbering scheme from the
// Activation API's service codes (lib/smspva-services.ts) - the same code
// means a different service depending on which API you're calling. E.g.
// opt77 is "Gameflip" under Activation but "1xbet" under Rental. Never mix
// the two files' codes across APIs.
//
// No logo URLs are documented for the Rental service list (unlike
// Activation, which links smspva.com-hosted icons), so hasCustomLogo is
// false throughout - SmspvaServiceIcon falls back to an initials badge.
import { SmspvaService } from "./types";

function svc(name: string, code: string): SmspvaService {
  const id = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return { id, code, name, logoUrl: "", hasCustomLogo: false };
}

export const SMSPVA_RENT_SERVICES: SmspvaService[] = [
  svc("1xbet", "opt77"),
  svc("Airbnb", "opt46"),
  svc("airtm", "opt204"),
  svc("airwallex.com", "opt161"),
  svc("Alibaba Group (TaoBao, AliPay, etc)", "opt61"),
  svc("Amazon", "opt44"),
  svc("American Airlines", "opt239"),
  svc("Apple", "opt154"),
  svc("astropay.com", "opt102"),
  svc("bankera.com", "opt45"),
  svc("Batery.in (baterybet)", "opt184"),
  svc("Bazos", "opt193"),
  svc("bet365", "opt43"),
  svc("Betano", "opt210"),
  svc("betcris.mx", "opt229"),
  svc("betly", "opt231"),
  svc("betwinner3.com", "opt51"),
  svc("Binance", "opt10"),
  svc("bit2me", "opt203"),
  svc("Bitget", "opt236"),
  svc("Bitnovo", "opt207"),
  svc("Bitpanda", "opt199"),
  svc("BITSA | BITSO", "opt57"),
  svc("blackcatcard", "opt144"),
  svc("Blizzard (+battle.net)", "opt3"),
  svc("booking", "opt88"),
  svc("Bovada", "opt214"),
  svc("bpay.md", "opt232"),
  svc("Brighty.app", "opt213"),
  svc("Bumble.com", "opt165"),
  svc("CoinBase", "opt70"),
  svc("Crypto.com", "opt56"),
  svc("Discord", "opt147"),
  svc("DPD UK", "opt221"),
  svc("enel.it", "opt224"),
  svc("EUROBET", "opt68"),
  svc("Facebook", "opt2"),
  svc("Fbet", "opt171"),
  svc("Fiverr", "opt6"),
  svc("fonbet", "opt158"),
  svc("Foxpay", "opt190"),
  svc("gemini.com", "opt54"),
  svc("GLOBAL66", "opt230"),
  svc("Google (GMail, YTube, etc.)", "opt1"),
  svc("Green Dot", "opt220"),
  svc("Guavapay (+Myguava)", "opt152"),
  svc("HardRock.bet", "opt223"),
  svc("Hinge", "opt185"),
  svc("huobi.com", "opt150"),
  svc("iCard", "opt99"),
  svc("Indeed.com", "opt34"),
  svc("Instagram (+Threads)", "opt16"),
  svc("JD.com", "opt198"),
  svc("Joust2trade", "opt92"),
  svc("KCEX", "opt201"),
  svc("Kleinanzeigen", "opt178"),
  svc("Kraken", "opt81"),
  svc("kucoin/bybit", "opt166"),
  svc("Leboncoin", "opt216"),
  svc("LINE", "opt32"),
  svc("LinkedIn", "opt8"),
  svc("Lottomatica.it (Better, Goldbet, Betflag)", "opt175"),
  svc("Lydia (+Sumeria)", "opt167"),
  svc("Mangopay", "opt240"),
  svc("match.com", "opt96"),
  svc("Microsoft (Azure, Bing, HotMail, etc.)", "opt15"),
  svc("mobileDE", "opt222"),
  svc("moneygram.com", "opt35"),
  svc("Moneyjar", "opt140"),
  svc("MoneyLion", "opt75"),
  svc("Moneytopay", "opt162"),
  svc("mooneygroup.it", "opt183"),
  svc("Mostbet", "opt143"),
  svc("MyBookie", "opt191"),
  svc("NCSOFT", "opt211"),
  svc("Neteller", "opt1001"),
  svc("NETFLIX", "opt225"),
  svc("nexo.io", "opt26"),
  svc("okcupid", "opt48"),
  svc("okx.com", "opt95"),
  svc("OnShop", "opt235"),
  svc("opinionoutpost", "opt28"),
  svc("OTHER", "opt142"),
  svc("ourtime.com", "opt27"),
  svc("Outlier", "opt217"),
  svc("P0F", "opt84"),
  svc("Paxful (Noone)", "opt72"),
  svc("paynet.md", "opt234"),
  svc("Payoneer", "opt103"),
  svc("PayPal + Ebay", "opt83"),
  svc("Paysafecard (+Mojeplatnosci)", "opt90"),
  svc("PaySend", "opt38"),
  svc("paytend", "opt159"),
  svc("Payz", "opt205"),
  svc("Payzy", "opt196"),
  svc("pecunpay", "opt202"),
  svc("Phyre", "opt93"),
  svc("plazo.es", "opt145"),
  svc("Pointsbet & Betmgm & Chime & Schwab", "opt37"),
  svc("Pyypl", "opt42"),
  svc("Rebet.com", "opt218"),
  svc("RedotPay", "opt208"),
  svc("relayfi.com", "opt53"),
  svc("Revolut", "opt101"),
  svc("REWARDCARD", "opt219"),
  svc("riamoneytransfer", "opt60"),
  svc("Signal", "opt153"),
  svc("sisal", "opt155"),
  svc("Skrill", "opt74"),
  svc("Steam", "opt58"),
  svc("Swagbucks", "opt173"),
  svc("T1nder", "opt9"),
  svc("Taptap", "opt212"),
  svc("Telegram", "opt29"),
  svc("Ticketmaster", "opt146"),
  svc("TikTok", "opt104"),
  svc("toloka.ai", "opt237"),
  svc("TransferGo", "opt180"),
  svc("Twilio & eToro", "opt66"),
  svc("ValuedOpinions", "opt39"),
  svc("Venmo", "opt85"),
  svc("Verse", "opt17"),
  svc("Viber", "opt11"),
  svc("Vinted", "opt31"),
  svc("Vivastreet", "opt67"),
  svc("Vivid", "opt100"),
  svc("Volet (Advcash)", "opt78"),
  svc("VRBO.com", "opt169"),
  svc("wallester.com", "opt149"),
  svc("Walmart", "opt192"),
  svc("WebMoney & ENUM", "opt24"),
  svc("weex", "opt226"),
  svc("westernunion", "opt82"),
  svc("WhatsAPP", "opt20"),
  svc("Willhaben", "opt163"),
  svc("Wirex", "opt7"),
  svc("Wise (TransferWise)", "opt0"),
  svc("WorldRemit", "opt228"),
  svc("X (Twitter)", "opt41"),
  svc("Yahoo", "opt65"),
];
