// Full real-world country reference (name, ISO code for flags, dial code) -
// generated from ISO 3166-1 + ITU calling codes, not scraped from any single
// provider's docs page (which we already caught missing Nigeria and India).
//
// IMPORTANT: this list is NOT a claim that SMSPVA stocks numbers for every
// country below. It's the full reference set used for names/flags/dial codes.
// Real per-service availability is decided live via get_count_new - see
// lib/mock-data.ts buildListings() TODO for where that call plugs in. Once
// wired, a country only ever appears as pickable for a service if the live
// API actually returns stock for that exact country+service pair.
import { SmspvaCountry } from "./types";

export const SMSPVA_COUNTRIES: SmspvaCountry[] = [
  { code: "AF", isoCode: "af", name: "Afghanistan", dialCode: "+93" },
  { code: "AL", isoCode: "al", name: "Albania", dialCode: "+355" },
  { code: "DZ", isoCode: "dz", name: "Algeria", dialCode: "+213" },
  { code: "AS", isoCode: "as", name: "American Samoa", dialCode: "+1" },
  { code: "AD", isoCode: "ad", name: "Andorra", dialCode: "+376" },
  { code: "AO", isoCode: "ao", name: "Angola", dialCode: "+244" },
  { code: "AI", isoCode: "ai", name: "Anguilla", dialCode: "+1" },
  { code: "AG", isoCode: "ag", name: "Antigua and Barbuda", dialCode: "+1" },
  { code: "AR", isoCode: "ar", name: "Argentina", dialCode: "+54" },
  { code: "AM", isoCode: "am", name: "Armenia", dialCode: "+374" },
  { code: "AW", isoCode: "aw", name: "Aruba", dialCode: "+297" },
  { code: "AU", isoCode: "au", name: "Australia", dialCode: "+61" },
  { code: "AT", isoCode: "at", name: "Austria", dialCode: "+43" },
  { code: "AZ", isoCode: "az", name: "Azerbaijan", dialCode: "+994" },
  { code: "BS", isoCode: "bs", name: "Bahamas", dialCode: "+1" },
  { code: "BH", isoCode: "bh", name: "Bahrain", dialCode: "+973" },
  { code: "BD", isoCode: "bd", name: "Bangladesh", dialCode: "+880" },
  { code: "BB", isoCode: "bb", name: "Barbados", dialCode: "+1" },
  { code: "BY", isoCode: "by", name: "Belarus", dialCode: "+375" },
  { code: "BE", isoCode: "be", name: "Belgium", dialCode: "+32" },
  { code: "BZ", isoCode: "bz", name: "Belize", dialCode: "+501" },
  { code: "BJ", isoCode: "bj", name: "Benin", dialCode: "+229" },
  { code: "BM", isoCode: "bm", name: "Bermuda", dialCode: "+1" },
  { code: "BT", isoCode: "bt", name: "Bhutan", dialCode: "+975" },
  { code: "BO", isoCode: "bo", name: "Bolivia", dialCode: "+591" },
  { code: "BQ", isoCode: "bq", name: "Bonaire, Sint Eustatius and Saba", dialCode: "+599" },
  { code: "BA", isoCode: "ba", name: "Bosnia and Herzegovina", dialCode: "+387" },
  { code: "BW", isoCode: "bw", name: "Botswana", dialCode: "+267" },
  { code: "BR", isoCode: "br", name: "Brazil", dialCode: "+55" },
  { code: "IO", isoCode: "io", name: "British Indian Ocean Territory", dialCode: "+246" },
  { code: "BN", isoCode: "bn", name: "Brunei Darussalam", dialCode: "+673" },
  { code: "BG", isoCode: "bg", name: "Bulgaria", dialCode: "+359" },
  { code: "BF", isoCode: "bf", name: "Burkina Faso", dialCode: "+226" },
  { code: "BI", isoCode: "bi", name: "Burundi", dialCode: "+257" },
  { code: "CV", isoCode: "cv", name: "Cabo Verde", dialCode: "+238" },
  { code: "KH", isoCode: "kh", name: "Cambodia", dialCode: "+855" },
  { code: "CM", isoCode: "cm", name: "Cameroon", dialCode: "+237" },
  { code: "CA", isoCode: "ca", name: "Canada", dialCode: "+1" },
  { code: "KY", isoCode: "ky", name: "Cayman Islands", dialCode: "+1" },
  { code: "CF", isoCode: "cf", name: "Central African Republic", dialCode: "+236" },
  { code: "TD", isoCode: "td", name: "Chad", dialCode: "+235" },
  { code: "CL", isoCode: "cl", name: "Chile", dialCode: "+56" },
  { code: "CN", isoCode: "cn", name: "China", dialCode: "+86" },
  { code: "CX", isoCode: "cx", name: "Christmas Island", dialCode: "+61" },
  { code: "CC", isoCode: "cc", name: "Cocos (Keeling) Islands", dialCode: "+61" },
  { code: "CO", isoCode: "co", name: "Colombia", dialCode: "+57" },
  { code: "KM", isoCode: "km", name: "Comoros", dialCode: "+269" },
  { code: "CG", isoCode: "cg", name: "Congo", dialCode: "+242" },
  { code: "CD", isoCode: "cd", name: "Congo, The Democratic Republic of the", dialCode: "+243" },
  { code: "CK", isoCode: "ck", name: "Cook Islands", dialCode: "+682" },
  { code: "CR", isoCode: "cr", name: "Costa Rica", dialCode: "+506" },
  { code: "HR", isoCode: "hr", name: "Croatia", dialCode: "+385" },
  { code: "CU", isoCode: "cu", name: "Cuba", dialCode: "+53" },
  { code: "CW", isoCode: "cw", name: "Curaçao", dialCode: "+599" },
  { code: "CY", isoCode: "cy", name: "Cyprus", dialCode: "+357" },
  { code: "CZ", isoCode: "cz", name: "Czechia", dialCode: "+420" },
  { code: "CI", isoCode: "ci", name: "Côte d'Ivoire", dialCode: "+225" },
  { code: "DK", isoCode: "dk", name: "Denmark", dialCode: "+45" },
  { code: "DJ", isoCode: "dj", name: "Djibouti", dialCode: "+253" },
  { code: "DM", isoCode: "dm", name: "Dominica", dialCode: "+1" },
  { code: "DO", isoCode: "do", name: "Dominican Republic", dialCode: "+1" },
  { code: "EC", isoCode: "ec", name: "Ecuador", dialCode: "+593" },
  { code: "EG", isoCode: "eg", name: "Egypt", dialCode: "+20" },
  { code: "SV", isoCode: "sv", name: "El Salvador", dialCode: "+503" },
  { code: "GQ", isoCode: "gq", name: "Equatorial Guinea", dialCode: "+240" },
  { code: "ER", isoCode: "er", name: "Eritrea", dialCode: "+291" },
  { code: "EE", isoCode: "ee", name: "Estonia", dialCode: "+372" },
  { code: "SZ", isoCode: "sz", name: "Eswatini", dialCode: "+268" },
  { code: "ET", isoCode: "et", name: "Ethiopia", dialCode: "+251" },
  { code: "FK", isoCode: "fk", name: "Falkland Islands (Malvinas)", dialCode: "+500" },
  { code: "FO", isoCode: "fo", name: "Faroe Islands", dialCode: "+298" },
  { code: "FJ", isoCode: "fj", name: "Fiji", dialCode: "+679" },
  { code: "FI", isoCode: "fi", name: "Finland", dialCode: "+358" },
  { code: "FR", isoCode: "fr", name: "France", dialCode: "+33" },
  { code: "GF", isoCode: "gf", name: "French Guiana", dialCode: "+594" },
  { code: "PF", isoCode: "pf", name: "French Polynesia", dialCode: "+689" },
  { code: "GA", isoCode: "ga", name: "Gabon", dialCode: "+241" },
  { code: "GM", isoCode: "gm", name: "Gambia", dialCode: "+220" },
  { code: "GE", isoCode: "ge", name: "Georgia", dialCode: "+995" },
  { code: "DE", isoCode: "de", name: "Germany", dialCode: "+49" },
  { code: "GH", isoCode: "gh", name: "Ghana", dialCode: "+233" },
  { code: "GI", isoCode: "gi", name: "Gibraltar", dialCode: "+350" },
  { code: "GR", isoCode: "gr", name: "Greece", dialCode: "+30" },
  { code: "GL", isoCode: "gl", name: "Greenland", dialCode: "+299" },
  { code: "GD", isoCode: "gd", name: "Grenada", dialCode: "+1" },
  { code: "GP", isoCode: "gp", name: "Guadeloupe", dialCode: "+590" },
  { code: "GU", isoCode: "gu", name: "Guam", dialCode: "+1" },
  { code: "GT", isoCode: "gt", name: "Guatemala", dialCode: "+502" },
  { code: "GG", isoCode: "gg", name: "Guernsey", dialCode: "+44" },
  { code: "GN", isoCode: "gn", name: "Guinea", dialCode: "+224" },
  { code: "GW", isoCode: "gw", name: "Guinea-Bissau", dialCode: "+245" },
  { code: "GY", isoCode: "gy", name: "Guyana", dialCode: "+592" },
  { code: "HT", isoCode: "ht", name: "Haiti", dialCode: "+509" },
  { code: "VA", isoCode: "va", name: "Holy See (Vatican City State)", dialCode: "+39" },
  { code: "HN", isoCode: "hn", name: "Honduras", dialCode: "+504" },
  { code: "HK", isoCode: "hk", name: "Hong Kong", dialCode: "+852" },
  { code: "HU", isoCode: "hu", name: "Hungary", dialCode: "+36" },
  { code: "IS", isoCode: "is", name: "Iceland", dialCode: "+354" },
  { code: "IN", isoCode: "in", name: "India", dialCode: "+91" },
  { code: "ID", isoCode: "id", name: "Indonesia", dialCode: "+62" },
  { code: "IR", isoCode: "ir", name: "Iran", dialCode: "+98" },
  { code: "IQ", isoCode: "iq", name: "Iraq", dialCode: "+964" },
  { code: "IE", isoCode: "ie", name: "Ireland", dialCode: "+353" },
  { code: "IM", isoCode: "im", name: "Isle of Man", dialCode: "+44" },
  { code: "IL", isoCode: "il", name: "Israel", dialCode: "+972" },
  { code: "IT", isoCode: "it", name: "Italy", dialCode: "+39" },
  { code: "JM", isoCode: "jm", name: "Jamaica", dialCode: "+1" },
  { code: "JP", isoCode: "jp", name: "Japan", dialCode: "+81" },
  { code: "JE", isoCode: "je", name: "Jersey", dialCode: "+44" },
  { code: "JO", isoCode: "jo", name: "Jordan", dialCode: "+962" },
  { code: "KZ", isoCode: "kz", name: "Kazakhstan", dialCode: "+7" },
  { code: "KE", isoCode: "ke", name: "Kenya", dialCode: "+254" },
  { code: "KI", isoCode: "ki", name: "Kiribati", dialCode: "+686" },
  { code: "KW", isoCode: "kw", name: "Kuwait", dialCode: "+965" },
  { code: "KG", isoCode: "kg", name: "Kyrgyzstan", dialCode: "+996" },
  { code: "LA", isoCode: "la", name: "Laos", dialCode: "+856" },
  { code: "LV", isoCode: "lv", name: "Latvia", dialCode: "+371" },
  { code: "LB", isoCode: "lb", name: "Lebanon", dialCode: "+961" },
  { code: "LS", isoCode: "ls", name: "Lesotho", dialCode: "+266" },
  { code: "LR", isoCode: "lr", name: "Liberia", dialCode: "+231" },
  { code: "LY", isoCode: "ly", name: "Libya", dialCode: "+218" },
  { code: "LI", isoCode: "li", name: "Liechtenstein", dialCode: "+423" },
  { code: "LT", isoCode: "lt", name: "Lithuania", dialCode: "+370" },
  { code: "LU", isoCode: "lu", name: "Luxembourg", dialCode: "+352" },
  { code: "MO", isoCode: "mo", name: "Macao", dialCode: "+853" },
  { code: "MG", isoCode: "mg", name: "Madagascar", dialCode: "+261" },
  { code: "MW", isoCode: "mw", name: "Malawi", dialCode: "+265" },
  { code: "MY", isoCode: "my", name: "Malaysia", dialCode: "+60" },
  { code: "MV", isoCode: "mv", name: "Maldives", dialCode: "+960" },
  { code: "ML", isoCode: "ml", name: "Mali", dialCode: "+223" },
  { code: "MT", isoCode: "mt", name: "Malta", dialCode: "+356" },
  { code: "MH", isoCode: "mh", name: "Marshall Islands", dialCode: "+692" },
  { code: "MQ", isoCode: "mq", name: "Martinique", dialCode: "+596" },
  { code: "MR", isoCode: "mr", name: "Mauritania", dialCode: "+222" },
  { code: "MU", isoCode: "mu", name: "Mauritius", dialCode: "+230" },
  { code: "YT", isoCode: "yt", name: "Mayotte", dialCode: "+262" },
  { code: "MX", isoCode: "mx", name: "Mexico", dialCode: "+52" },
  { code: "FM", isoCode: "fm", name: "Micronesia, Federated States of", dialCode: "+691" },
  { code: "MD", isoCode: "md", name: "Moldova", dialCode: "+373" },
  { code: "MC", isoCode: "mc", name: "Monaco", dialCode: "+377" },
  { code: "MN", isoCode: "mn", name: "Mongolia", dialCode: "+976" },
  { code: "ME", isoCode: "me", name: "Montenegro", dialCode: "+382" },
  { code: "MS", isoCode: "ms", name: "Montserrat", dialCode: "+1" },
  { code: "MA", isoCode: "ma", name: "Morocco", dialCode: "+212" },
  { code: "MZ", isoCode: "mz", name: "Mozambique", dialCode: "+258" },
  { code: "MM", isoCode: "mm", name: "Myanmar", dialCode: "+95" },
  { code: "NA", isoCode: "na", name: "Namibia", dialCode: "+264" },
  { code: "NR", isoCode: "nr", name: "Nauru", dialCode: "+674" },
  { code: "NP", isoCode: "np", name: "Nepal", dialCode: "+977" },
  { code: "NL", isoCode: "nl", name: "Netherlands", dialCode: "+31" },
  { code: "NC", isoCode: "nc", name: "New Caledonia", dialCode: "+687" },
  { code: "NZ", isoCode: "nz", name: "New Zealand", dialCode: "+64" },
  { code: "NI", isoCode: "ni", name: "Nicaragua", dialCode: "+505" },
  { code: "NE", isoCode: "ne", name: "Niger", dialCode: "+227" },
  { code: "NG", isoCode: "ng", name: "Nigeria", dialCode: "+234" },
  { code: "NU", isoCode: "nu", name: "Niue", dialCode: "+683" },
  { code: "NF", isoCode: "nf", name: "Norfolk Island", dialCode: "+672" },
  { code: "KP", isoCode: "kp", name: "North Korea", dialCode: "+850" },
  { code: "MK", isoCode: "mk", name: "North Macedonia", dialCode: "+389" },
  { code: "MP", isoCode: "mp", name: "Northern Mariana Islands", dialCode: "+1" },
  { code: "NO", isoCode: "no", name: "Norway", dialCode: "+47" },
  { code: "OM", isoCode: "om", name: "Oman", dialCode: "+968" },
  { code: "PK", isoCode: "pk", name: "Pakistan", dialCode: "+92" },
  { code: "PW", isoCode: "pw", name: "Palau", dialCode: "+680" },
  { code: "PS", isoCode: "ps", name: "Palestine, State of", dialCode: "+970" },
  { code: "PA", isoCode: "pa", name: "Panama", dialCode: "+507" },
  { code: "PG", isoCode: "pg", name: "Papua New Guinea", dialCode: "+675" },
  { code: "PY", isoCode: "py", name: "Paraguay", dialCode: "+595" },
  { code: "PE", isoCode: "pe", name: "Peru", dialCode: "+51" },
  { code: "PH", isoCode: "ph", name: "Philippines", dialCode: "+63" },
  { code: "PL", isoCode: "pl", name: "Poland", dialCode: "+48" },
  { code: "PT", isoCode: "pt", name: "Portugal", dialCode: "+351" },
  { code: "PR", isoCode: "pr", name: "Puerto Rico", dialCode: "+1" },
  { code: "QA", isoCode: "qa", name: "Qatar", dialCode: "+974" },
  { code: "RO", isoCode: "ro", name: "Romania", dialCode: "+40" },
  { code: "RU", isoCode: "ru", name: "Russian Federation", dialCode: "+7" },
  { code: "RW", isoCode: "rw", name: "Rwanda", dialCode: "+250" },
  { code: "RE", isoCode: "re", name: "Réunion", dialCode: "+262" },
  { code: "BL", isoCode: "bl", name: "Saint Barthélemy", dialCode: "+590" },
  { code: "SH", isoCode: "sh", name: "Saint Helena, Ascension and Tristan da Cunha", dialCode: "+290" },
  { code: "KN", isoCode: "kn", name: "Saint Kitts and Nevis", dialCode: "+1" },
  { code: "LC", isoCode: "lc", name: "Saint Lucia", dialCode: "+1" },
  { code: "MF", isoCode: "mf", name: "Saint Martin (French part)", dialCode: "+590" },
  { code: "PM", isoCode: "pm", name: "Saint Pierre and Miquelon", dialCode: "+508" },
  { code: "VC", isoCode: "vc", name: "Saint Vincent and the Grenadines", dialCode: "+1" },
  { code: "WS", isoCode: "ws", name: "Samoa", dialCode: "+685" },
  { code: "SM", isoCode: "sm", name: "San Marino", dialCode: "+378" },
  { code: "ST", isoCode: "st", name: "Sao Tome and Principe", dialCode: "+239" },
  { code: "SA", isoCode: "sa", name: "Saudi Arabia", dialCode: "+966" },
  { code: "SN", isoCode: "sn", name: "Senegal", dialCode: "+221" },
  { code: "RS", isoCode: "rs", name: "Serbia", dialCode: "+381" },
  { code: "SC", isoCode: "sc", name: "Seychelles", dialCode: "+248" },
  { code: "SL", isoCode: "sl", name: "Sierra Leone", dialCode: "+232" },
  { code: "SG", isoCode: "sg", name: "Singapore", dialCode: "+65" },
  { code: "SX", isoCode: "sx", name: "Sint Maarten (Dutch part)", dialCode: "+1" },
  { code: "SK", isoCode: "sk", name: "Slovakia", dialCode: "+421" },
  { code: "SI", isoCode: "si", name: "Slovenia", dialCode: "+386" },
  { code: "SB", isoCode: "sb", name: "Solomon Islands", dialCode: "+677" },
  { code: "SO", isoCode: "so", name: "Somalia", dialCode: "+252" },
  { code: "ZA", isoCode: "za", name: "South Africa", dialCode: "+27" },
  { code: "KR", isoCode: "kr", name: "South Korea", dialCode: "+82" },
  { code: "SS", isoCode: "ss", name: "South Sudan", dialCode: "+211" },
  { code: "ES", isoCode: "es", name: "Spain", dialCode: "+34" },
  { code: "LK", isoCode: "lk", name: "Sri Lanka", dialCode: "+94" },
  { code: "SD", isoCode: "sd", name: "Sudan", dialCode: "+249" },
  { code: "SR", isoCode: "sr", name: "Suriname", dialCode: "+597" },
  { code: "SJ", isoCode: "sj", name: "Svalbard and Jan Mayen", dialCode: "+47" },
  { code: "SE", isoCode: "se", name: "Sweden", dialCode: "+46" },
  { code: "CH", isoCode: "ch", name: "Switzerland", dialCode: "+41" },
  { code: "SY", isoCode: "sy", name: "Syria", dialCode: "+963" },
  { code: "TW", isoCode: "tw", name: "Taiwan", dialCode: "+886" },
  { code: "TJ", isoCode: "tj", name: "Tajikistan", dialCode: "+992" },
  { code: "TZ", isoCode: "tz", name: "Tanzania", dialCode: "+255" },
  { code: "TH", isoCode: "th", name: "Thailand", dialCode: "+66" },
  { code: "TL", isoCode: "tl", name: "Timor-Leste", dialCode: "+670" },
  { code: "TG", isoCode: "tg", name: "Togo", dialCode: "+228" },
  { code: "TK", isoCode: "tk", name: "Tokelau", dialCode: "+690" },
  { code: "TO", isoCode: "to", name: "Tonga", dialCode: "+676" },
  { code: "TT", isoCode: "tt", name: "Trinidad and Tobago", dialCode: "+1" },
  { code: "TN", isoCode: "tn", name: "Tunisia", dialCode: "+216" },
  { code: "TM", isoCode: "tm", name: "Turkmenistan", dialCode: "+993" },
  { code: "TC", isoCode: "tc", name: "Turks and Caicos Islands", dialCode: "+1" },
  { code: "TV", isoCode: "tv", name: "Tuvalu", dialCode: "+688" },
  { code: "TR", isoCode: "tr", name: "Türkiye", dialCode: "+90" },
  { code: "UG", isoCode: "ug", name: "Uganda", dialCode: "+256" },
  { code: "UA", isoCode: "ua", name: "Ukraine", dialCode: "+380" },
  { code: "AE", isoCode: "ae", name: "United Arab Emirates", dialCode: "+971" },
  { code: "UK", isoCode: "gb", name: "United Kingdom", dialCode: "+44" },
  { code: "US", isoCode: "us", name: "United States", dialCode: "+1" },
  { code: "UY", isoCode: "uy", name: "Uruguay", dialCode: "+598" },
  { code: "UZ", isoCode: "uz", name: "Uzbekistan", dialCode: "+998" },
  { code: "VU", isoCode: "vu", name: "Vanuatu", dialCode: "+678" },
  { code: "VE", isoCode: "ve", name: "Venezuela", dialCode: "+58" },
  { code: "VN", isoCode: "vn", name: "Vietnam", dialCode: "+84" },
  { code: "VG", isoCode: "vg", name: "Virgin Islands, British", dialCode: "+1" },
  { code: "VI", isoCode: "vi", name: "Virgin Islands, U.S.", dialCode: "+1" },
  { code: "WF", isoCode: "wf", name: "Wallis and Futuna", dialCode: "+681" },
  { code: "EH", isoCode: "eh", name: "Western Sahara", dialCode: "+212" },
  { code: "YE", isoCode: "ye", name: "Yemen", dialCode: "+967" },
  { code: "ZM", isoCode: "zm", name: "Zambia", dialCode: "+260" },
  { code: "ZW", isoCode: "zw", name: "Zimbabwe", dialCode: "+263" },
  { code: "AX", isoCode: "ax", name: "Åland Islands", dialCode: "+358" },
];
